name: Basic

on: push

jobs:
  trial-job:
    runs-on: ubuntu-latest #mac, windows
    steps:
      - name: Print Hello
        run: echo Hello
  
  ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: ASCII welcome
        uses: mscoutermarsh/ascii-art-action@master
        with:
          text: 'You're welcome'
