name: Python Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python Script
    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pytest
          pip install -U scikit-learn
      - name: Run Script
        run: |
          python script.py
      - name: Run Tests
        run: pytest test.py

      - name: black
        uses: lgeiger/black-action@master
        with:
          args: .
      - name: CHeck for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push Changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'theSekyi'
          git config --global user.email 'thesekyi@user.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "automated changes"
          git push
